/**
 * Vellum Predict API
 * Documentation of API endpoints used to make predictions through Vellum
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class NormalizedTokenLogProbs {
    'token': string;
    'logprob': number | null;
    'topLogprobs': { [key: string]: number; } | null;
    'textOffset': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "token",
            "baseName": "token",
            "type": "string"
        },
        {
            "name": "logprob",
            "baseName": "logprob",
            "type": "number"
        },
        {
            "name": "topLogprobs",
            "baseName": "top_logprobs",
            "type": "{ [key: string]: number; }"
        },
        {
            "name": "textOffset",
            "baseName": "text_offset",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return NormalizedTokenLogProbs.attributeTypeMap;
    }
}

