/**
 * Vellum Client API
 * Documentation of API endpoints of Vellum
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SearchRequestOptionsRequest } from './searchRequestOptionsRequest';

export class SearchRequestBodyRequest {
    'indexId'?: string | null;
    'indexName'?: string | null;
    'query': string;
    'options'?: SearchRequestOptionsRequest | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "indexId",
            "baseName": "index_id",
            "type": "string"
        },
        {
            "name": "indexName",
            "baseName": "index_name",
            "type": "string"
        },
        {
            "name": "query",
            "baseName": "query",
            "type": "string"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "SearchRequestOptionsRequest"
        }    ];

    static getAttributeTypeMap() {
        return SearchRequestBodyRequest.attributeTypeMap;
    }
}

