/**
 * Vellum Client API
 * Documentation of API endpoints of Vellum
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SearchWeightsRequest } from './searchWeightsRequest';

export class SearchRequestOptionsRequest {
    'limit'?: number | null;
    'weights'?: SearchWeightsRequest | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number"
        },
        {
            "name": "weights",
            "baseName": "weights",
            "type": "SearchWeightsRequest"
        }    ];

    static getAttributeTypeMap() {
        return SearchRequestOptionsRequest.attributeTypeMap;
    }
}

