/**
 * Vellum Client API
 * Documentation of API endpoints of Vellum
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SearchWeightsRequest {
    'semanticSimilarity': number;
    'keywords': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "semanticSimilarity",
            "baseName": "semantic_similarity",
            "type": "number"
        },
        {
            "name": "keywords",
            "baseName": "keywords",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SearchWeightsRequest.attributeTypeMap;
    }
}

