/**
 * Vellum Client API
 * Documentation of API endpoints of Vellum
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UploadDocumentRequestBodyRequest {
    'addToIndexNames'?: Array<string> | null;
    'externalId'?: string | null;
    'label': string;
    'contents': RequestFile;
    'keywords'?: Array<string> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addToIndexNames",
            "baseName": "add_to_index_names",
            "type": "Array<string>"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "contents",
            "baseName": "contents",
            "type": "RequestFile"
        },
        {
            "name": "keywords",
            "baseName": "keywords",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return UploadDocumentRequestBodyRequest.attributeTypeMap;
    }
}

