/**
 * Vellum Client API
 * Documentation of API endpoints of Vellum
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UploadDocumentRequestBodyRequest {
    'indexId'?: string | null;
    'indexName'?: string | null;
    'externalId'?: string | null;
    'label': string;
    'file': RequestFile;
    'keywords'?: Array<string> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "indexId",
            "baseName": "index_id",
            "type": "string"
        },
        {
            "name": "indexName",
            "baseName": "index_name",
            "type": "string"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "file",
            "baseName": "file",
            "type": "RequestFile"
        },
        {
            "name": "keywords",
            "baseName": "keywords",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return UploadDocumentRequestBodyRequest.attributeTypeMap;
    }
}

